Update setup

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -3,6 +3,14 @@ set -euo pipefail
 IFS=$'\n\t'
 set -vx
 
+required_ruby_version=$(cat .ruby-version)
+if [ "$(ruby -v | grep -oP '\d+\.\d+\.\d+')" != "$required_ruby_version" ]; then
+  echo "Ruby version $required_ruby_version is required."
+  exit 1
+fi
+
 bundle install
 
 # Do any other automated setup that you need to do here
+
+echo "Setup completed!"
